use crate::tcp_message::{TcpReceiverMessage, TcpSenderMessage};
use crate::tcp_receiver::TcpReceiver;
use crate::tcp_segment::TcpSegment;
use crate::tcp_sender::{TcpSender, TcpSenderConfig};
use crate::wrapping_integers::Wrap32;

/// Configuration for one TCP connection direction pair.
///
/// This object represents one local TCP endpoint talking to one peer endpoint.
/// It does not know about IP addresses yet. IP wrapping happens later in
/// `ipv4_datagram.rs` and the future `tcp_ipv4.rs`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TcpConnectionConfig {
    pub local_port: u16,
    pub peer_port: u16,
    pub sender_capacity: usize,
    pub receiver_capacity: usize,
    pub isn: Wrap32,
    pub sender_config: TcpSenderConfig,
}

impl TcpConnectionConfig {
    pub fn new(
        local_port: u16,
        peer_port: u16,
        sender_capacity: usize,
        receiver_capacity: usize,
        isn: Wrap32,
        sender_config: TcpSenderConfig,
    ) -> Self {
        Self {
            local_port,
            peer_port,
            sender_capacity,
            receiver_capacity,
            isn,
            sender_config,
        }
    }
}

/// A minimal full-duplex TCP peer core.
///
/// It combines:
///
/// - local sender: sends local application bytes to the peer
/// - local receiver: receives peer bytes and produces ACK/window feedback
///
/// It outputs and consumes `TcpSegment`.
///
/// Later, `TcpSegment` will be wrapped inside `Ipv4Datagram`,
/// and then written to/read from a TUN device.
#[derive(Debug)]
pub struct TcpConnection {
    local_port: u16,
    peer_port: u16,

    sender: TcpSender,
    receiver: TcpReceiver,
}

impl TcpConnection {
    pub fn new(config: TcpConnectionConfig) -> Self {
        assert!(config.local_port != 0, "local TCP port cannot be zero");
        assert!(config.peer_port != 0, "peer TCP port cannot be zero");

        Self {
            local_port: config.local_port,
            peer_port: config.peer_port,
            sender: TcpSender::new(config.sender_capacity, config.isn, config.sender_config),
            receiver: TcpReceiver::new(config.receiver_capacity),
        }
    }

    pub fn local_port(&self) -> u16 {
        self.local_port
    }

    pub fn peer_port(&self) -> u16 {
        self.peer_port
    }

    pub fn sender(&self) -> &TcpSender {
        &self.sender
    }

    pub fn sender_mut(&mut self) -> &mut TcpSender {
        &mut self.sender
    }

    pub fn receiver(&self) -> &TcpReceiver {
        &self.receiver
    }

    pub fn receiver_mut(&mut self) -> &mut TcpReceiver {
        &mut self.receiver
    }

    /// Current receiver feedback generated by this endpoint.
    ///
    /// This is what should be piggybacked on outgoing TCP segments.
    pub fn receiver_message(&self) -> TcpReceiverMessage {
        self.receiver.send()
    }

    /// Current empty sender message generated by this endpoint.
    ///
    /// Useful when we need to emit a pure ACK.
    pub fn empty_sender_message(&self) -> TcpSenderMessage {
        self.sender.make_empty_message()
    }

    /// True after both:
    ///
    /// - this endpoint has sent SYN and had it ACKed
    /// - this endpoint has received the peer's SYN
    ///
    /// This is a simplified established check suitable for this project.
    pub fn is_established(&self) -> bool {
        self.sender.syn_sent() && self.sender.snd_una() > 0 && self.receiver.send().ackno.is_some()
    }

    pub fn bytes_in_flight(&self) -> u64 {
        self.sender.bytes_in_flight()
    }

    pub fn outstanding_segments(&self) -> usize {
        self.sender.outstanding_segments()
    }

    pub fn is_finished(&self) -> bool {
        self.sender.is_finished()
    }

    /// Active open: produce an initial SYN.
    ///
    /// Client side usually calls this first.
    pub fn connect(&mut self) -> Vec<TcpSegment> {
        self.flush_sender()
    }

    /// Application writes bytes into the outbound stream.
    ///
    /// Returns:
    ///
    /// - number of bytes accepted into ByteStream
    /// - TCP segments generated by this write
    pub fn write(&mut self, data: &[u8]) -> (usize, Vec<TcpSegment>) {
        let bytes_written = self.sender.outbound_mut().push(data);
        let segments = self.flush_sender();

        (bytes_written, segments)
    }

    /// Application closes its outbound stream.
    ///
    /// This may generate a FIN if the send window has space.
    pub fn close(&mut self) -> Vec<TcpSegment> {
        self.sender.outbound_mut().close();
        self.flush_sender()
    }

    /// Process one incoming TCP segment and return any outgoing response.
    ///
    /// This handles both halves:
    ///
    /// - incoming ACK/window feedback goes to local sender
    /// - incoming SYN/payload/FIN/RST goes to local receiver
    ///
    /// If the incoming segment occupies sequence space but we have no data to
    /// send, this method emits a pure ACK.
    pub fn receive_segment(&mut self, segment: TcpSegment) -> Vec<TcpSegment> {
        if !self.belongs_to_this_connection(&segment) {
            return Vec::new();
        }

        let incoming_sender_message = segment.to_sender_message();
        let incoming_receiver_message = segment.to_receiver_message();

        let incoming_sequence_len = incoming_sender_message.sequence_length();

        // First process ACK/window information for our local sender.
        //
        // If the segment has no ACK flag, `ackno` is None. The sender may still
        // learn the peer's advertised window.
        self.sender.receive(incoming_receiver_message);

        // Then process peer data/control information for our local receiver.
        if incoming_sequence_len > 0 || incoming_sender_message.rst {
            self.receiver.receive(incoming_sender_message);
        }

        // Try to piggyback ACK on any outgoing sender data.
        let mut outgoing = self.flush_sender();

        // If peer sent SYN/payload/FIN but we had no sender data to piggyback
        // on, generate a pure ACK.
        if incoming_sequence_len > 0 && outgoing.is_empty() {
            if let Some(ack) = self.make_pure_ack_segment() {
                outgoing.push(ack);
            }
        }

        outgoing
    }

    /// Advance time and emit retransmissions when needed.
    pub fn tick(&mut self, elapsed_ms: u64) -> Vec<TcpSegment> {
        let local_port = self.local_port;
        let peer_port = self.peer_port;
        let receiver_feedback = self.receiver.send();

        let mut outgoing = Vec::new();

        self.sender.tick(elapsed_ms, |sender_message| {
            outgoing.push(Self::build_segment(
                local_port,
                peer_port,
                sender_message,
                receiver_feedback,
            ));
        });

        outgoing
    }

    /// Attempt to send any pending sender data.
    ///
    /// Every outgoing segment piggybacks the latest ACK/window feedback from
    /// the local receiver.
    pub fn flush_sender(&mut self) -> Vec<TcpSegment> {
        let local_port = self.local_port;
        let peer_port = self.peer_port;
        let receiver_feedback = self.receiver.send();

        let mut outgoing = Vec::new();

        self.sender.push(|sender_message| {
            outgoing.push(Self::build_segment(
                local_port,
                peer_port,
                sender_message,
                receiver_feedback,
            ));
        });

        outgoing
    }

    fn belongs_to_this_connection(&self, segment: &TcpSegment) -> bool {
        segment.header.src_port == self.peer_port && segment.header.dst_port == self.local_port
    }

    fn make_pure_ack_segment(&self) -> Option<TcpSegment> {
        let receiver_feedback = self.receiver.send();

        if receiver_feedback.ackno.is_none() && !receiver_feedback.rst {
            return None;
        }

        let sender_message = self.sender.make_empty_message();

        Some(Self::build_segment(
            self.local_port,
            self.peer_port,
            sender_message,
            receiver_feedback,
        ))
    }

    fn build_segment(
        local_port: u16,
        peer_port: u16,
        sender_message: TcpSenderMessage,
        receiver_feedback: TcpReceiverMessage,
    ) -> TcpSegment {
        TcpSegment::from_messages(
            local_port,
            peer_port,
            &sender_message,
            Some(receiver_feedback),
        )
    }
}

#[cfg(test)]
mod tests {
    use bytes::Bytes;

    use super::*;

    fn sender_config() -> TcpSenderConfig {
        TcpSenderConfig {
            initial_rto_ms: 100,
            max_timer_interval_ms: 10_000,
            max_payload_size: 4,
        }
    }

    fn client() -> TcpConnection {
        TcpConnection::new(TcpConnectionConfig::new(
            50_000,
            80,
            128,
            128,
            Wrap32::new(1_000),
            sender_config(),
        ))
    }

    fn server() -> TcpConnection {
        TcpConnection::new(TcpConnectionConfig::new(
            80,
            50_000,
            128,
            128,
            Wrap32::new(9_000),
            sender_config(),
        ))
    }

    #[test]
    fn active_open_sends_syn() {
        let mut client = client();

        let segments = client.connect();

        assert_eq!(segments.len(), 1);

        let syn = &segments[0];

        assert_eq!(syn.header.src_port, 50_000);
        assert_eq!(syn.header.dst_port, 80);
        assert_eq!(syn.header.seqno, Wrap32::new(1_000));
        assert!(syn.header.syn);
        assert!(!syn.header.fin);
        assert_eq!(syn.payload, Bytes::new());
        assert_eq!(client.bytes_in_flight(), 1);
    }

    #[test]
    fn passive_open_replies_with_syn_ack() {
        let mut client = client();
        let mut server = server();

        let syn = client.connect().remove(0);

        let response = server.receive_segment(syn);

        assert_eq!(response.len(), 1);

        let syn_ack = &response[0];

        assert_eq!(syn_ack.header.src_port, 80);
        assert_eq!(syn_ack.header.dst_port, 50_000);
        assert_eq!(syn_ack.header.seqno, Wrap32::new(9_000));
        assert_eq!(syn_ack.header.ackno, Some(Wrap32::new(1_001)));
        assert!(syn_ack.header.syn);
        assert!(!syn_ack.header.fin);

        assert_eq!(server.bytes_in_flight(), 1);
    }

    #[test]
    fn three_way_handshake_reaches_established_state() {
        let mut client = client();
        let mut server = server();

        let syn = client.connect().remove(0);

        let syn_ack = server.receive_segment(syn).remove(0);

        let client_ack = client.receive_segment(syn_ack);

        assert_eq!(client_ack.len(), 1);
        assert_eq!(client_ack[0].header.ackno, Some(Wrap32::new(9_001)));
        assert!(!client_ack[0].header.syn);
        assert!(client_ack[0].payload.is_empty());

        let server_response = server.receive_segment(client_ack[0].clone());

        assert!(server_response.is_empty());

        assert!(client.is_established());
        assert!(server.is_established());

        assert_eq!(client.bytes_in_flight(), 0);
        assert_eq!(server.bytes_in_flight(), 0);
    }

    #[test]
    fn client_data_is_acked_by_server() {
        let mut client = client();
        let mut server = server();

        complete_handshake(&mut client, &mut server);

        let (written, data_segments) = client.write(b"hello");

        assert_eq!(written, 5);
        assert_eq!(data_segments.len(), 2);

        assert_eq!(data_segments[0].payload, Bytes::from_static(b"hell"));
        assert_eq!(data_segments[0].header.seqno, Wrap32::new(1_001));
        assert_eq!(data_segments[0].header.ackno, Some(Wrap32::new(9_001)));

        assert_eq!(data_segments[1].payload, Bytes::from_static(b"o"));
        assert_eq!(data_segments[1].header.seqno, Wrap32::new(1_005));

        let ack1 = server.receive_segment(data_segments[0].clone());
        assert_eq!(ack1.len(), 1);
        assert_eq!(ack1[0].header.ackno, Some(Wrap32::new(1_005)));

        let ack2 = server.receive_segment(data_segments[1].clone());
        assert_eq!(ack2.len(), 1);
        assert_eq!(ack2[0].header.ackno, Some(Wrap32::new(1_006)));

        client.receive_segment(ack1[0].clone());
        client.receive_segment(ack2[0].clone());

        assert_eq!(client.bytes_in_flight(), 0);
    }

    #[test]
    fn data_ack_can_be_piggybacked_on_sender_data() {
        let mut client = client();
        let mut server = server();

        complete_handshake(&mut client, &mut server);

        let (_, client_data) = client.write(b"abc");
        assert_eq!(client_data.len(), 1);

        let (_, server_pending_data) = server.write(b"xyz");

        // Server has now sent its own data. ACK for client's incoming data
        // can be piggybacked on outgoing server data.
        assert_eq!(server_pending_data.len(), 1);

        let server_response = server.receive_segment(client_data[0].clone());

        if server_response.is_empty() {
            // This can happen if server data was already sent before receiving
            // client's data. In this implementation, piggybacking happens only
            // on segments generated after processing the incoming segment.
            let pure_ack = server.receive_segment(client_data[0].clone());
            assert!(pure_ack.len() <= 1);
        } else {
            assert_eq!(server_response[0].header.ackno, Some(Wrap32::new(1_004)));
        }
    }

    #[test]
    fn close_sends_fin_and_peer_acks_it() {
        let mut client = client();
        let mut server = server();

        complete_handshake(&mut client, &mut server);

        let fin_segments = client.close();

        assert_eq!(fin_segments.len(), 1);
        assert!(fin_segments[0].header.fin);
        assert_eq!(fin_segments[0].header.seqno, Wrap32::new(1_001));

        let server_ack = server.receive_segment(fin_segments[0].clone());

        assert_eq!(server_ack.len(), 1);
        assert_eq!(server_ack[0].header.ackno, Some(Wrap32::new(1_002)));

        client.receive_segment(server_ack[0].clone());

        assert!(client.is_finished());
    }

    #[test]
    fn retransmission_reemits_oldest_outstanding_segment() {
        let mut client = client();

        let syn = client.connect().remove(0);

        let retransmissions = client.tick(100);

        assert_eq!(retransmissions.len(), 1);

        assert_eq!(retransmissions[0].header.seqno, syn.header.seqno);
        assert!(retransmissions[0].header.syn);

        assert_eq!(client.sender().consecutive_retransmissions(), 1);
        assert_eq!(client.sender().current_rto_ms(), 200);
    }

    #[test]
    fn wrong_ports_are_ignored() {
        let mut client = client();

        let mut bad = TcpSegment::from_messages(
            1234,
            5678,
            &TcpSenderMessage {
                seqno: Wrap32::new(1),
                syn: true,
                payload: Bytes::new(),
                fin: false,
                rst: false,
            },
            None,
        );

        bad.header.src_port = 1234;
        bad.header.dst_port = 5678;

        let response = client.receive_segment(bad);

        assert!(response.is_empty());
        assert_eq!(client.bytes_in_flight(), 0);
    }

    fn complete_handshake(client: &mut TcpConnection, server: &mut TcpConnection) {
        let syn = client.connect().remove(0);
        let syn_ack = server.receive_segment(syn).remove(0);
        let ack = client.receive_segment(syn_ack).remove(0);
        let response = server.receive_segment(ack);

        assert!(response.is_empty());
        assert!(client.is_established());
        assert!(server.is_established());
    }
}
